baseURL = 'https://lemorsephotography.tech/'
languageCode = 'fr-FR'
title = 'LeMorsePhotography'

[taxonomies]
    species = "species"
    locations = "locations"

[params]
    imgproxy_base = "http://localhost:8080"
